PAINTROID-304 Fixed text field reset issue
Catrobat/Paintroid pull request #1010
Opened 2021-09-24 18:41 UTC by yugalkishore59

https://jira.catrob.at/browse/PAINTROID-304?jql=project%20%3D%20PAINTROID%20AND%20status%20%3D%20%22Bug%20Backlog%22

Added new variables to store values of current width, height and position of the text field and then assigned these variables back to the text field after creating bitmap in order to restore the last attributes of the text field (in case of font and font effect change).

As mentioned in the above issue (PAINTROID-304), now the dimensions of the text field don't reset when either font or font effect is changed.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behaviour
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-11-18 14:18 UTC, ThorstenBandel commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +                toolPosition.set(position)
And a Test that checks for this change would be needed as well

2021-11-19 07:30 UTC, yugalkishore59 commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +                toolPosition.set(position)
Now I've removed that extra white space as suggested.

2021-11-30 11:30 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +                boxHeight = height
Could you please create a new function for these lines as these same lines are being duplicated in 3-4 methods?

2021-11-30 11:35 UTC, CodeChamp-SS requested changes
The changes LGTM and work as expected. 3 of the tests in TextToolIntegrationTest are failing on Jenkins, could you please fix them? Also could you please create a new test for testing the new behavior?

2021-12-12 13:00 UTC, yugalkishore59 commented
As suggested, now I've created a function named keepAttributeAndcreateBitmap() to minimize the repetition of code lines.

2021-12-12 13:24 UTC, CodeChamp-SS commented
> As suggested, now I've created a function named keepAttributeAndcreateBitmap() to minimize the repetition of code lines.

Thanks, the changes LGTM now! And what about the test, are you writing one? Otherwise, I'll approve the changes.

2021-12-12 13:30 UTC, yugalkishore59 commented
Well, I kinda don't know much about Jenkins. Is there much of a need?

2021-12-12 13:41 UTC, CodeChamp-SS commented
> Well, I kinda don't know much about Jenkins. Is there much of a need?
> 
> > > As suggested, now I've created a function named keepAttributeAndcreateBitmap() to minimize the repetition of code lines.
> > 
> > 
> > Thanks, the changes LGTM now! Just noticed a minor static analysis warning on Jenkins, could you please fix that? And what about the test, are you writing one? Otherwise, I'll approve the changes.

yeah, it's a must, it's just one line fix.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/52480794/145714665-a0a89d3a-e1d1-45ab-ad64-edaa061d02a8.png">

2021-12-12 13:51 UTC, yugalkishore59 commented
> > Well, I kinda don't know much about Jenkins. Is there much of a need?
> > > > As suggested, now I've created a function named keepAttributeAndcreateBitmap() to minimize the repetition of code lines.
> > > 
> > > 
> > > Thanks, the changes LGTM now! Just noticed a minor static analysis warning on Jenkins, could you please fix that? And what about the test, are you writing one? Otherwise, I'll approve the changes.
> 
> yeah, it's a must, it's just one line fix. <img alt="image" width="1030" src="https://user-images.githubusercontent.com/52480794/145714665-a0a89d3a-e1d1-45ab-ad64-edaa061d02a8.png">

Oh, I didn't see that. Is it good now?

2021-12-12 14:05 UTC, CodeChamp-SS commented
> > > Well, I kinda don't know much about Jenkins. Is there much of a need?
> > > > > As suggested, now I've created a function named keepAttributeAndcreateBitmap() to minimize the repetition of code lines.
> > > > 
> > > > 
> > > > Thanks, the changes LGTM now! Just noticed a minor static analysis warning on Jenkins, could you please fix that? And what about the test, are you writing one? Otherwise, I'll approve the changes.
> > 
> > 
> > yeah, it's a must, it's just one line fix. <img alt="image" width="1030" src="https://user-images.githubusercontent.com/52480794/145714665-a0a89d3a-e1d1-45ab-ad64-edaa061d02a8.png">
> 
> Oh, I didn't see that. Is it good now?

yes, thanks :)

2021-12-12 14:10 UTC, yugalkishore59 commented
You’re welcome. It was the least I could do. :D

2022-07-17 16:07 UTC, ThorstenBandel commented
Already fixed in another PR, but thanks for the contribution :)

2022-07-17 16:07 UTC, closed without merging