PAINTROID-382: "+" icon not appearing in line tool after drawing the first line segment
Catrobat/Paintroid pull request #1033
Opened 2022-01-07 09:13 UTC by JulianJautz

"+" didn't not appear when line was drawn in one swipe
(https://jira.catrob.at/browse/PAINTROID-382)

* setting startpoint plus endpoint and drawing a line was handled differently
* drawing a line in one swipe behaves now like setting startpoint and endpoint separately
* also fixes:
   PAINTROID-383: Line tool does not allow to correctly reposition end point of first segment
   (https://jira.catrob.at/browse/PAINTROID-383)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-01-10 22:05 UTC, barcodepony approved these changes
Changes and Tests look good to me, now works as intented! 👍 

Failed tests in CI/CD appeare to be flaky and can be ignored.

2022-01-18 16:23 UTC, wslany requested changes
Thanks! However, the functionality is still not correct, as follows:

1. Select the line tool, then touch the screen at point A and, while continuing to touch the screen, move your finger around on the screen towards point B. 
2. Observe that, correctly, the first line is drawn starting from A to B and continuously updated to the latest touch position B.
3. Remove the finger from the screen, then tap at a new position C.
4. Observe that _incorrectly_ a second line segment is drawn from B to C. Instead, the expected behavior would be to update B of the first segment to the new end position C, so that there is a single line segment from A to C, since neither the checkmark nor the "+" button was touched, and the first segment (starting from A) has not yet been finished. 
5. Note that sometimes, the first line segment is deleted, and sometimes it remains. It is unclear what actions influence whether this first segment remains or disappears. 

Another, probably unrelated problem:

1. Using the line tool, draw a first segment from point A to point B by tapping on position A then on position B. Then tap on a third position C. 
2. Observe that, as expected, the segment is continuously updated from A to the latest point C. Tapping can be repeated several times.
3. Now touch the screen at another position, D, and, without removing the finger from the screen, move the finger to another position E. 
4. Observe that during this movement (while the finger still touches the screen), a second segment is _incorrectly_ drawn between points D and E. Instead, the expected behavior should have been to update the first segment from A to E, as in the first step, since neither "+" nor the checkmark have yet been tapped, and the first segment was not yet finalized. 

Another issue, though I guess this one is probably the same as the one above:

1. Draw a first line segment from point A to B, then tap on "+".
2. Touch the screen at another position C and move your finger to position D, without removing the finger from the screen.
3. Observe that during this movement, a line is _incorrectly_ drawn and continuously updated from C to D. Instead, the correct, expected behavior should be that when the screen is touched initially at point C in step 2 above, the second segment is drawn from B to C, and then continuously updated starting from B to the finger's latest position, until the finger is removed from the screen.

2022-01-18 16:25 UTC, wslany commented
> Changes and Tests look good to me, now works as intented! 👍
> 
> Failed tests in CI/CD appeare to be flaky and can be ignored.

@barcodepony your reviews somehow are not accepted as reviews by github. Maybe add an explicit positive review to make it stick? See below how to do that:
![image](https://user-images.githubusercontent.com/1747888/149977235-a94c0ffd-ce3c-451a-bc9a-9d037cfaa3a6.png)

2022-02-06 08:53 UTC, wslany commented
@barcodepony Are the changes fine from a code-review point of view? I checked the functionality (including pinch zoom, undo redo, and switch of tools or colors), and from that perspective everything works fine now (@JulianJautz , awesome work!), but I didn't check test coverage etc. Please @barcodepony , can you do one (hopefully last) code-review round? 

🙏 Please also make sure to tap on "approve" in case you approve so that your approval is registered by the system.

2022-02-07 08:35 UTC, barcodepony commented
@wslany the code works implements the behaviour now correctly and is also properly tested.
Personally, I just don't think that the new variables in `LineTool.kt` are a pretty solution. Especially `fromMove` is not very self explanatory. From a technical point of view the PR is fine, unclear if is should approve this in regard of the "code style" or if it's better if @JulianJautz can find a better name for one or both variables in question. Looking at the code in e.g. 1 year definitely could raise some questions.

@JulianJautz could you rename the variables quickly to resolve the issue? :+1:

2022-02-07 08:41 UTC, barcodepony commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
> +    var fromMove = false
i suggest renaming these to variables to make there functionality more clear, especially `fromMove` does not give a lot of insight. `firstMove` could be renamed aswell to make it obvious that it's used for connected lines :smiley:

2022-02-07 08:42 UTC, barcodepony requested changes
Please see my comment for `LineTook.kt` (:

2022-02-07 11:29 UTC, JulianJautz commented
> @wslany the code works implements the behaviour now correctly and is also properly tested. Personally, I just don't think that the new variables in `LineTool.kt` are a pretty solution. Especially `fromMove` is not very self explanatory. From a technical point of view the PR is fine, unclear if is should approve this in regard of the "code style" or if it's better if @JulianJautz can find a better name for one or both variables in question. Looking at the code in e.g. 1 year definitely could raise some questions.
> 
> @JulianJautz could you rename the variables quickly to resolve the issue? 👍

@barcodepony I changed the names now, but to really understand the behaviour, it would need more than a better name, I think. Should I add comments? And would you have had an idea for a different approach as I can imagine that there are better solutions. But I couldn't figure out another way to differentiate between taps and swipes, which is necessary already while drawing...

2022-02-07 11:57 UTC, barcodepony commented
> > @wslany the code works implements the behaviour now correctly and is also properly tested. Personally, I just don't think that the new variables in `LineTool.kt` are a pretty solution. Especially `fromMove` is not very self explanatory. From a technical point of view the PR is fine, unclear if is should approve this in regard of the "code style" or if it's better if @JulianJautz can find a better name for one or both variables in question. Looking at the code in e.g. 1 year definitely could raise some questions.
> > @JulianJautz could you rename the variables quickly to resolve the issue? 👍
> 
> @barcodepony I changed the names now, but to really understand the behaviour, it would need more than a better name, I think. Should I add comments? And would you have had an idea for a different approach as I can imagine that there are better solutions. But I couldn't figure out another way to differentiate between taps and swipes, which is necessary already while drawing...

@JulianJautz to the best of my knowledge, comments are undesired in catrobat projects and the code should speak for itself.
The new names are way better and I think we can now leave it like that with the new changes. I managed to figured out the code behaviour with the old names as well, so it should be good enough to approve the changes.

Regarding a different ideas: I do not see any obvious alternative approaches, my main concern is that we need two new state variables. What could be done is a refactor with e.g. a state enum for better indication of what a certain function should do in the given situation - but a refactor like this outside the responsibilites of the ticket.

Changes approved! 😄👍

2022-02-07 11:57 UTC, barcodepony approved these changes

2022-02-10 08:23 UTC, wslany approved these changes

2022-02-10 08:23 UTC, merged

2022-02-10 08:26 UTC, wslany commented
Thanks!!!! Super!