PAINTROID-323 When image is loaded and then saved, the program detect…
Catrobat/Paintroid pull request #1038
Opened 2022-02-03 15:01 UTC by AneiMakovec

PAINTROID-323 When image is loaded and then saved, the program detects that the file exists and ask to overwrite

An existing loaded image is now recognized properly when trying to overwrite it, but the overwrite action still ads a (1) after the file extension.

2022-06-28 10:32 UTC, FromG requested changes
looks good to me. refactoring needed

2022-06-28 15:10 UTC, FromG approved these changes
ok

2022-07-25 14:06 UTC, FromG approved these changes
ok

2022-07-31 16:42 UTC, ThorstenBandel approved these changes
LGTM Thanks!

2022-07-31 16:43 UTC, merged