PAINTROID-291: Color changes cannot be undone or redone
Catrobat/Paintroid pull request #1044
Opened 2022-03-09 21:45 UTC by JulianJautz

color changes weren't considered as commands and not added to CommandManager

* implemented a ColorChangedCommand
* ColorChangedCommand is added to CommandManager when color is selected in ColorPickerDialog
* adapted undo/redo behaviour in line tool to work with ColorCommands

(https://jira.catrob.at/browse/PAINTROID-291)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-03-23 11:38 UTC, illo1311 requested changes
Looks fine to me, but please resolve the merge conflict :)

2022-04-26 13:59 UTC, illo1311 approved these changes
lgtm

2022-05-07 16:34 UTC, wslany requested changes
I found several crashes, as follows: 

- On Android 8 to Android 12, when the color is changed _at least once,_ then when I save the image in the .catrobat-image format, there is an error while saving shown on the screen (this error only appears when there are color changes --- if the color stays the black one, then it works fine; also when it is a different format like png), as follows:
![image](https://user-images.githubusercontent.com/1747888/167262362-2ec3bcde-578a-4f44-beb1-9b183e07bd3c.png)

The catrobat-image file is nevertheless written to the file system, but when I try to open that image using the "Load image" option of Paintroid, the app crashes with the following stack trace:
```
05-07 18:06:03.916 E/AndroidRuntime( 1746): FATAL EXCEPTION: DefaultDispatcher-worker-3
05-07 18:06:03.916 E/AndroidRuntime( 1746): FATAL EXCEPTION: DefaultDispatcher-worker-3
05-07 18:06:03.916 E/AndroidRuntime( 1746): Process: org.catrobat.paintroid.independent_20220506_1943, PID: 1746
05-07 18:06:03.916 E/AndroidRuntime( 1746): com.esotericsoftware.kryo.KryoException: Buffer underflow.
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.io.Input.require(Input.java:219)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:407)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:145)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.readCurrentVersion(CommandManagerModelSerializer.kt:47)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.readCurrentVersion(CommandManagerModelSerializer.kt:27)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV3(VersionSerializer.kt:53)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV2(VersionSerializer.kt:50)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV1(VersionSerializer.kt:47)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.handleVersions(VersionSerializer.kt:37)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.read(CommandManagerModelSerializer.kt:39)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.read(CommandManagerModelSerializer.kt:27)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:777)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandSerializationUtilities.readFromFile(CommandSerializationUtilities.kt:194)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage.getBitmapReturnValue(LoadImage.kt:65)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage.access$getBitmapReturnValue(LoadImage.kt:37)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage$execute$1.invokeSuspend(LoadImage.kt:99)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
05-07 18:06:03.916 E/AndroidRuntime( 1746): Process: org.catrobat.paintroid.independent_20220506_1943, PID: 1746
05-07 18:06:03.916 E/AndroidRuntime( 1746): com.esotericsoftware.kryo.KryoException: Buffer underflow.
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.io.Input.require(Input.java:219)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:407)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:145)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.readCurrentVersion(CommandManagerModelSerializer.kt:47)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.readCurrentVersion(CommandManagerModelSerializer.kt:27)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV3(VersionSerializer.kt:53)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV2(VersionSerializer.kt:50)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.readV1(VersionSerializer.kt:47)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.VersionSerializer.handleVersions(VersionSerializer.kt:37)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.read(CommandManagerModelSerializer.kt:39)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandManagerModelSerializer.read(CommandManagerModelSerializer.kt:27)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:777)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.command.serialization.CommandSerializationUtilities.readFromFile(CommandSerializationUtilities.kt:194)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage.getBitmapReturnValue(LoadImage.kt:65)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage.access$getBitmapReturnValue(LoadImage.kt:37)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at org.catrobat.paintroid.iotasks.LoadImage$execute$1.invokeSuspend(LoadImage.kt:99)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
05-07 18:06:03.916 E/AndroidRuntime( 1746): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
05-07 18:06:03.916 E/AndroidRuntime( 1746): Process: org.catrobat.paintro [...]

2022-05-19 11:34 UTC, FromG requested changes

2022-05-19 11:34 UTC, FromG commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/junit/command/DefaultCommandFactoryTest.java
> +	}
this test seems to fail. 
createColorChangedCommand wants a context as second parameter.
Therefore jenkins can't run the ticket.

2022-05-31 09:51 UTC, FromG approved these changes
everything should work.

2022-06-06 13:18 UTC, wslany approved these changes

2022-06-06 13:26 UTC, wslany commented
@AneiMakovec wrote:
> I took a look at PAINTROID-291 and tested the code. I used multiple different tools while changing the colors and the undo and redo operations performed as expected for both changing the color with the color picker or with the pipette in the color picker. The only thing that I noticed was that when using the pipette tool (the standalone tool, not the one in color picker) the color changes were not remembered as a command. I don't know if this is really an issue, since the ticket description mentions only the color picker and its pipette. As for the tests, I ran them locally and they passed. I also checked the test code and it seems to test multiple use cases, but I didn't find any tests regarding the pipette in the color picker. I don't know if we can even test the pipette, so I'm not sure if this is an issue either.

Thanks Anei for doing the QA check. I think you are right, it would have been better if the color-checkpoints of the pipette tool were also included. Having said that, the fix covers a large amount of the original ticket, so it now works fine in most situations. Also, regarding tests for the pipette in the color picker, it is true but at the same time it is nearly impossible to test all possible scenarios, so I guess the current test coverage is good enough. Another consideration is that @JulianJautz who implemented the fix is currently not with the team and has no time to further optimize the implementation, so based on all this I am now merging it.

Thanks everyone who was involved in fixing and giving feedback and testing this PR!

2022-06-06 13:27 UTC, merged