PAINTROID-304
Catrobat/Paintroid pull request #1067
Opened 2022-04-11 08:58 UTC by Electronix1337

After this ticket the text toolbox will now automatically adjust the text size when the user resizes this window. Works from all corners of the toolbox (bottomright, bottomleft, topleft, topright).

https://jira.catrob.at/browse/PAINTROID-304

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-04-22 13:42 UTC, JulianJautz submitted a review, later dismissed
As far as I understand the description in the ticket, the goal is that the size of the textbox doesn't change after the font was set to bold, italic,... (and not the font size itself). This is not what your implementation does.
Do I miss something?

And I also noticed that this change in size also happens, when the font is changed or "text" in the bottom bar is clicked, so always when something in the text tool related menu is changed.

2022-04-28 09:06 UTC, Electronix1337 commented
> As far as I understand the description in the ticket, the goal is that the size of the textbox doesn't change after the font was set to bold, italic,... (and not the font size itself). This is not what your implementation does. Do I miss something?
> 
> And I also noticed that this change in size also happens, when the font is changed or "text" in the bottom bar is clicked, so always when something in the text tool related menu is changed.

You are right, but I talked to Thorsten before I started implementing the ticket and we both came to the same conclusion that the only reasonable solution to this would be to automatically adjust the font size when text box is resized using corner points. As the changes in font type and text style are applied to the text with the internal font size I would have to calculate the proportional difference when resizing but this seems like an overkill to me or rather counterintuitive in comparison to my implementation. I also don't see a proper use case where users want to distort the text field only in X or Y (so all resizing points except the corners) and then change the font type or text style as a distorted text is rarely the desired outcome. So in short, if a user resizes the text box and applies a change in font type or text style the desired outcome would be that the text box stays the same in size, which happens with my implementation and for this to properly work, I need to internally adjust the font size as the changes are made based on this. Hope it's clear what I mean with this.

2022-04-30 14:46 UTC, JulianJautz commented
I think I understand. So resizing via the corners seems to work as you described.
And the text box shrinkage after setting bold, italic,... won't be changed (when resizing box before only in x or y direction)?

> > And I also noticed that this change in size also happens, when the font is changed or "text" in the bottom bar is clicked, so always when something in the text tool related menu is changed.
> 
> I don't really get what you mean with this, could you further describe that please.
I meant that the box also shrinks when clicking on "Tools" or "Text" in the footer (box size change in x or y direction before). I think it would be good to not change the text box size when clicking these buttons.

2022-06-22 15:20 UTC, StanglTobias requested changes
There are still some problems when the text is italic

![Screenshot_20220622_171909](https://user-images.githubusercontent.com/22729383/175068366-6c57fbcb-676b-4651-9fd7-e859b2b07a12.png)

2022-06-22 15:20 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +    var wasItalicRecentlyDisabled = false
can be removed

2022-06-23 13:41 UTC, StanglTobias approved these changes

2022-06-24 07:15 UTC, CodeChamp-SS requested changes
The changes work as expected. Please look into the suggested changes (just for cleaning up the code a bit). Then I'll approve the PR.

2022-06-24 07:15 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
>          }
You can write this also as suggested in `TextToolCommand.kt`.

2022-06-24 07:15 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +    }
```suggestion
    private fun storeAttributes(italic: Boolean = false) {
        if (italic) {
            boxWidth *= ITALIC_FONT_BOX_ADJUSTMENT
        }
        oldBoxWidth = boxWidth
        oldBoxHeight = boxHeight
        oldToolPosition = PointF(toolPosition.x, toolPosition.y)
    }

    private fun applyAttributes(italic: Boolean = false) {
        boxWidth = oldBoxWidth / if (italic) ITALIC_FONT_BOX_ADJUSTMENT else 1f
        boxHeight = oldBoxHeight
        if (oldToolPosition != null) {
            toolPosition = oldToolPosition as PointF
        } else {
            resetBoxPosition()
        }
    }
```
You can write it like this, to remove duplicity and clean up the code.

2022-06-24 07:16 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/command/implementation/TextToolCommand.kt
> +                }
I think you also remove line 77 and use that directly inside the `drawText()` method in place of that `x`.

2022-06-24 15:24 UTC, CodeChamp-SS approved these changes
LGTM!

2022-06-24 15:39 UTC, CodeChamp-SS reviewed
Please look into these other minor changes :)

2022-06-24 15:39 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TextTool.kt
> +    var callback: TextToolOptionsView.Callback? = null
I think this `callback` var can be removed, as it isn't getting used anywhere.

2022-06-27 10:56 UTC, CodeChamp-SS approved these changes

2022-06-27 12:49 UTC, merged