PAINTROID-199 simplify layer moving and merging
Catrobat/Paintroid pull request #1073
Opened 2022-04-21 12:41 UTC by StanglTobias

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-04-21 21:02 UTC, JulianJautz requested changes
LGTM

I think changing the design of the eye/checkbox column was a good idea. Maybe a slight color change between visible and not-visible icon could indicate the difference even more clearly?

Why did you use the six points as drag&drop icon and not the "grip" icon suggested in the task?

Eraser tests pass locally, don't know why they failed on jenkins

2022-04-22 06:53 UTC, StanglTobias commented
> Maybe a slight color change between visible and not-visible icon could indicate the difference even more clearly?
Good idea, but let's wait for a PO review if my suggested adaptions to the design are fine.

> Why did you use the six points as drag&drop icon and not the "grip" icon suggested in the task?
I think Paintroid is also great because of its small app size, so i decided to go for Material Design Vector Drawable instead of a PNG.

2022-04-22 07:09 UTC, JulianJautz approved these changes

2022-04-22 11:53 UTC, wslany commented
In Catroid we recently changed all ripple touch areas to vector drawables, see, e.g., https://github.com/Catrobat/Catroid/pull/4288/files#diff-5ab9a13eec5e957075e63a736c2a5f0c6c0c2ef4fbc7095d98ded4695209240f --- I would prefer if we could keep it here as well, if that is feasible.

2022-04-22 12:24 UTC, wslany requested changes
If possible, please switch to the checkbox for visibility.

2022-04-22 12:45 UTC, StanglTobias commented
> In Catroid we recently changed all ripple touch areas to vector drawables, see, e.g., https://github.com/Catrobat/Catroid/pull/4288/files#diff-5ab9a13eec5e957075e63a736c2a5f0c6c0c2ef4fbc7095d98ded4695209240f --- I would prefer if we could keep it here as well, if that is feasible.

The Drag Icon is a VectorDrawable, but i guess you just meant to replace the icon. 

> If possible, please switch to the checkbox for visibility.

ooookay

2022-04-22 12:47 UTC, StanglTobias commented
@wslany i guess this will not need another code review since there were just minor changes in the XML by replacing icons

2022-04-25 05:07 UTC, JulianJautz requested changes
the "eye"-icon in the header of the layer menu is missing, otherwise it looks and works like described in the ticket

2022-05-09 15:28 UTC, JulianJautz approved these changes

2022-05-09 15:29 UTC, JulianJautz commented
> the "eye"-icon in the header of the layer menu is missing, otherwise it looks and works like described in the ticket

lgtm
eye-icon is there again

2022-05-16 09:44 UTC, wslany approved these changes

2022-05-16 09:44 UTC, merged

2022-05-16 09:45 UTC, wslany commented
Thanks!