PAINTROID-460 test case refactor
Catrobat/Paintroid pull request #1123
Opened 2022-06-26 14:55 UTC by akebu6

Ticket: https://jira.catrob.at/browse/PAINTROID-460

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-12-06 17:49 UTC, juliajulie95 requested changes
Looks good, just have some small questions :)

2022-12-06 18:37 UTC, akebu6 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/LanguageSupport.kt
> +@file:Suppress("DEPRECATION")
Okay, I shall make the requested changes

2022-12-06 18:46 UTC, akebu6 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/CustomSwiper.kt
> +@file:Suppress("SameParameterValue")
this was added because the variable "step" 's actual value will always be CustomeSwiper.STEPS. Should I remove it?

2022-12-06 18:47 UTC, akebu6 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/CustomSwiper.kt
> +                    if (timeUntilDesired > 10) { uiController.loopMainThreadForAtLeast(timeUntilDesired) }
what do you want it reformatted to?

2022-12-06 18:50 UTC, akebu6 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/OffsetLocationProvider.kt
> +    @Suppress("unused")
this was the version of Android Studio I was using at the time. It was giving warnings so I added it to prevent that

2022-12-06 18:51 UTC, akebu6 commented
I made the changes that you requested but I only have the ones where I asked some questions. After they are concluded, I shall make them and push the changes

2022-12-08 09:27 UTC, juliajulie95 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/rtl/util/RtlUiTestUtils.kt
> +    init {
Yes

2022-12-08 09:28 UTC, juliajulie95 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/util/CustomSwiper.kt
> +                    if (timeUntilDesired > 10) { uiController.loopMainThreadForAtLeast(timeUntilDesired) }
Just use the reformatter from android studio :)
Braces should be on their own line

2022-12-08 09:59 UTC, akebu6 commented
Just pushed the changes requested

2023-05-13 16:51 UTC, closed without merging