PAINTROID-494 Change toolbaricon of stamp tool
Catrobat/Paintroid pull request #1164
Opened 2022-11-25 15:07 UTC by Lenkomotive

PAINTROID-494 Change toolbaricon of stamp tool

Refactor project and adapt to renaming of stamp tool to clipboard.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2022-12-10 10:36 UTC, juliajulie95 commented
Please do not manually change keys in the translation files (except of the base file)
The new translation keys will be uploaded to crowding and then the others will be automatically updated.
So if you now change the keys manually it will be overwritten anyways.
You might get analysis warnings fo the translation files, but I will merge the ticket and then sync with crowdin immedeately after and the warnings will disappear

2022-12-10 10:36 UTC, juliajulie95 commented
+ please resolve the conflicts

2023-01-03 15:47 UTC, juliajulie95 commented
@Lenkomotive 
Please undo the changes in the translation files as stated above

2023-01-03 17:37 UTC, juliajulie95 requested changes

2023-01-03 17:37 UTC, juliajulie95 commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ClipboardToolIntegrationTest.java
> -	@Test
Please do not delete tests

2023-01-03 17:46 UTC, Lenkomotive commented on Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/tools/ClipboardToolIntegrationTest.java
> -	@Test
ack

2023-01-25 15:03 UTC, SebastianGrief approved these changes
LGTM :+1:

2023-02-05 18:15 UTC, merged