PAINTROID-545 Zooming while cursor tool is down deletes the already drawn line
Catrobat/Paintroid pull request #1206
Opened 2023-02-08 19:09 UTC by bakicelebi

[PAINTROID-545](https://jira.catrob.at/browse/PAINTROID-545)

Fixed the bug, zooming while drawing with cursor does not delete the already drawn line anymore

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-02-13 20:24 UTC, Lenkomotive submitted a review, later dismissed

2023-02-17 10:12 UTC, exland approved these changes

2023-02-23 14:31 UTC, Lenkomotive requested changes
The same bug exists in the LineTool as well. Please check this out too.

2023-02-26 18:06 UTC, bakicelebi commented
@Lenkomotive fixed :+1:

2023-02-26 18:13 UTC, Lenkomotive approved these changes

2023-02-28 17:14 UTC, SebastianGrief approved these changes
LGTM 👍

2023-02-28 17:14 UTC, merged