PAINTROID-409 Update Splashscreen to new Splashscreen API(android 12)
Catrobat/Paintroid pull request #1214
Opened 2023-02-12 19:04 UTC by Aayush2111

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-02-12 19:13 UTC, Aayush2111 commented
Hey @ThorstenBandel 

I have deleted the previous pull request due to some errors.
I have taken the time to address these issues and have created a new pull request. The new pull request includes all of the necessary fixes and improvements!

2023-02-15 14:24 UTC, juliajulie95 commented
The icon seems to be cut off in your screenshots, please have a look

2023-03-27 12:05 UTC, SebastianGrief commented
I've tested this on a API 22 emulator and a device, both do not show the logo. 
Could you have a look at that please?

In the meantime, I'll try and find a solution for the image size problem.

2023-03-27 12:23 UTC, Aayush2111 commented
> I've tested this on a API 22 emulator and a device, both do not show the logo. Could you have a look at that please?
> 
> In the meantime, I'll try and find a solution for the image size problem.

I'll check that out again!

2023-03-27 12:25 UTC, Aayush2111 commented
> I've tested this on a API 22 emulator and a device, both do not show the logo. Could you have a look at that please?
> 
> In the meantime, I'll try and find a solution for the image size problem.

I'll check that out again!

2023-03-31 10:53 UTC, SebastianGrief commented
> > I've tested this on a API 22 emulator and a device, both do not show the logo. Could you have a look at that please?
> > In the meantime, I'll try and find a solution for the image size problem.
> 
> It seems to be functioning properly on my end. Have you attempted to manually open the application? It's possible that if the application was installed directly from Android Studio, any updates or modifications may not be reflected.

Did you test on an emulator or do you have a physical device with API 22?

2023-04-04 06:36 UTC, Aayush2111 commented
> > > I've tested this on a API 22 emulator and a device, both do not show the logo. Could you have a look at that please?
> > > In the meantime, I'll try and find a solution for the image size problem.
> > 
> > 
> > It seems to be functioning properly on my end. Have you attempted to manually open the application? It's possible that if the application was installed directly from Android Studio, any updates or modifications may not be reflected.
> 
> > Known incompatibilities:
> > [...]
> > On API 21-22, The icon isn't displayed until the application starts, only the background is visible.

I see. What shall be done for that then?

2023-07-11 13:38 UTC, foenabua requested changes

2023-07-11 13:38 UTC, foenabua commented on Paintroid/src/main/java/org/catrobat/paintroid/MainActivity.kt
> +        installSplashScreen()
in the [migration guide](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate#best-practices) it is noted to call installSplashScreen() before super.onCreate().
Please change this

2023-07-11 17:36 UTC, foenabua requested changes

2023-07-11 17:36 UTC, foenabua commented on Paintroid/build.gradle
> +    implementation 'androidx.core:core-splashscreen:1.0.0-beta02'
Please change version to androidx.core:core-splashscreen:1.0.1

2023-07-11 17:36 UTC, foenabua commented on build.gradle
> +    ext.kotlin_version = '1.6.0'
Please resolve merge conflicts. You can use kotlin v1.6.0

2023-07-11 17:36 UTC, foenabua commented on gradle.properties
> +kotlin.jvm.target.validation.mode = IGNORE
I didn't understand why you added kotlin.jvm.target.validation.mode = IGNORE. Could you please explain?

2023-09-26 15:09 UTC, juliajulie95 commented
Please reopen if you are still working on this.

2023-09-26 15:09 UTC, closed without merging