PAINTROID-548 : Selecting the already selected stroke type unselects it
Catrobat/Paintroid pull request #1218
Opened 2023-02-20 20:34 UTC by bakicelebi

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-02-23 13:39 UTC, Lenkomotive requested changes

2023-02-23 13:39 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptionsView.kt
> +        if (!buttonRect.isChecked) {
This If is unnecessary

2023-02-23 13:39 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultBrushToolOptionsView.kt
> +        if (!buttonCircle.isChecked) {
This If is unnecessary

2023-02-23 13:39 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
> +        if (!buttonRect.isChecked) {
This If is unnecessary

2023-02-23 13:39 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultSmudgeToolOptionsView.kt
> +        if (!buttonCircle.isChecked) {
This If is unnecessary

2023-02-23 13:41 UTC, Lenkomotive requested changes
Pls see comments

2023-02-23 14:19 UTC, exland approved these changes

2023-02-23 14:41 UTC, Lenkomotive approved these changes
👍🏼

2023-02-28 16:40 UTC, SebastianGrief approved these changes
LGTM 👍

2023-02-28 16:40 UTC, merged