PAINTROID-507 Fix ToolOnBackPressedIntegrationTests
Catrobat/Paintroid pull request #1223
Opened 2023-03-02 22:42 UTC by khalid-nasralla

[PAINTROID-507](https://jira.catrob.at/browse/PAINTROID-507)
1) testBrushToolBackPressedFromCatroidAndUsePicture: test works for me without any problems
2) testBrushToolBackPressedWithSaveAndOverride: the @After tearDown() was not enough cleaning up before execution of this test. Also there was a problem with the waiting in the test being too short so it probably had race conditions.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-03-15 20:49 UTC, bakicelebi requested changes
Tests seem to be working on jenkins but locally you have to manually delete the file that gets saved to retests it. It would be probably also a good idea to delete the file that gets saved in tearDown() method.

`File imageFile = new File("/storage/emulated/0/Pictures/" + defaultPictureName + ".png");
if (imageFile.exists()) {
    imageFile.delete();
}`

I added these two lines to tearDown() and it works locally now without needing to delete the image file manually. You might want to change the hardcoded path to image.

2023-03-16 07:10 UTC, khalid-nasralla commented
> Tests seem to be working on jenkins but locally you have to manually delete the file that gets saved to retest it. It would be probably also a good idea to delete the file that gets saved in tearDown() method.
> 
> `File imageFile = new File("/storage/emulated/0/Pictures/" + defaultPictureName + ".png"); if (imageFile.exists()) { imageFile.delete(); }`
> 
> I added these two lines to tearDown() and it works locally now without needing to delete the image file manually. You might want to change the hardcoded path to image.

done, now it also gets locally cleaned up in the tearDown()

2023-03-16 18:17 UTC, bakicelebi approved these changes
:+1:

2023-03-31 06:46 UTC, ThorstenBandel approved these changes

2023-03-31 06:46 UTC, merged