PAINTROID-185: Visibility of the text tool settings
Catrobat/Paintroid pull request #1252
Opened 2023-04-02 18:35 UTC by bakicelebi

[PAINTROID-185](https://jira.catrob.at/browse/PAINTROID-185)

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-04-03 20:20 UTC, Lenkomotive requested changes
Good work! I like the idea of not animating the handleDown action but only the onMove action, since the vanishing UI only makes sense while moving. Could you please check if this also makes sense for other tools as well?

Also, regarding TextTool. When clicking outside the Box, the button for toolspecific options does not make the options reappear. Hit me up if you need help reproducing the bug ;)

2023-04-13 23:56 UTC, bakicelebi commented
> Good work! I like the idea of not animating the handleDown action but only the onMove action, since the vanishing UI only makes sense while moving. Could you please check if this also makes sense for other tools as well?
> 
> Also, regarding TextTool. When clicking outside the Box, the button for toolspecific options does not make the options reappear. Hit me up if you need help reproducing the bug ;)

1. Done! Now tools hide top and bottom bar onMove instead of onDown.
2. Thank you, fixed.

2023-05-03 18:33 UTC, Lenkomotive approved these changes

2023-05-13 13:00 UTC, ThorstenBandel approved these changes

2023-05-13 13:01 UTC, merged