PAINTROID-607 Spraycan ignores alpha value
Catrobat/Paintroid pull request #1275
Opened 2023-05-15 13:12 UTC by Rd4dev

**[PAINTROID-607]**(https://jira.catrob.at/browse/PAINTROID-607)
Added spray tool to compatible new to get it working again.
Related and Replicated Fix from: https://github.com/Catrobat/Paintroid/pull/1198

**Fixed:** **PAINTROID-580**(https://jira.catrob.at/browse/PAINTROID-580)

**TestCases:**
Added 4 test cases for each Tool.
- Test a point on click with Black Color
- Test a point on click with Transparent/Alpha Color
- Test a point on move with Black Color
- Test a point on move with Transparent/Alpha Color

**SprayToolIntegrationTest:**
As Spray Tool creates spray points within the radius, it is difficult to test the color at a certain point.
So created a method (in SprayTool) to create a spray point at the current coordinate to make sure there is always a spray point to test on.

**DefaultZoomWindowController:**
Modified the if else nest to when() to reduce complexity

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-05-19 16:04 UTC, bakicelebi requested changes

2023-05-21 13:25 UTC, Rd4dev commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/zoomwindow/DefaultZoomWindowController.kt
> +            tool?.toolType?.name.equals(ToolType.SPRAY.name)
I have pushed the fix for [PAINTROID-580](https://jira.catrob.at/browse/PAINTROID-580), which includes the line `tool?.toolType?.name.equals(ToolType.BRUSH.name)`. I've also added test cases to cover these tools and updated the pull request description to reflect the changes made. Thank you for your suggestion!

2023-05-22 11:40 UTC, bakicelebi requested changes
1. The newly written tests pass without the fix too, because you set the color value to a hardcoded value with lower alpha value. 
2. I suggests changing the alpha value with the slider in colorpicker. See ColorDialogIntegrationTest.java ```public void alphaValueIsSetInSeekBarWhenChangedInSlider()``` for how this can be done.

2023-05-22 15:04 UTC, Rd4dev commented
@bakicelebi Thank you for taking the time to review the code. I value your feedback and appreciate it. I would like to address the issue of the tests passing without the fix by providing some clarification.

**Brush Tool Issue:** For the brush tool, the issue only occurs when dragging or moving the tool with alpha values. 
**Test Cases:** The test cases 
- `testBrushToolColor()`
- `testBrushToolWithHandleMoveColor()` and 
- `testBrushToolTransparentColor()`
are general test cases for the brush tool and would pass without the fix since they are not specifically related to this issue. 

**Related Test Case:** The **`testBrushToolWithHandleMoveTransparentColor()`** is the specific test case for the [fix](https://github.com/Catrobat/Paintroid/pull/1275).


Similarly, for the spray tool, 
**Brush Tool Issue:** The issue occurs both when clicking and dragging with alpha values. 
**Test Cases:** The test cases 
- `testSprayToolColor()` and 
- `testSprayToolWithHandleMoveColor()` 
are general test cases for the spray tool to test with a black color, which would pass without the fix. 

**Related Test Case:** The **`testSprayToolTransparentColor()`** and **`testSprayToolWithHandleMoveTransparentColor()`** are the two test cases specifically related to this fix.

I regret any confusion that may have arisen due to the inclusion of unrelated test cases in this pull request. If deemed unnecessary, I can certainly remove them. Furthermore, I have made the required adjustments to retrieve the alpha color values from the color picker rather than hardcoding them

Through thorough testing, I have observed that the mentioned three test cases 
1. **`testSprayToolTransparentColor()`**
2. **`testSprayToolWithHandleMoveTransparentColor()`**
3. **`testBrushToolWithHandleMoveTransparentColor())`** 
fail in the absence of the fix. 

However, upon implementing the fix, all test cases now pass successfully.

I would appreciate any further feedback or suggestions for changes if necessary!

2023-05-23 12:05 UTC, bakicelebi approved these changes
Thank you for clarification. :+1:

2023-05-30 16:10 UTC, khalid-nasralla commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt
Hey RD, code looks good to me. Also the solution with the mid point for testing purposes of the SprayTool is good.

The only thing that I think should be changed is the usage of the "!!" operator in line 234/235 since we are trying to avoid it. It can be used in tests though. You could use the elvis-operator instead for example, as it is done in line 226 or 227.

2023-05-31 08:27 UTC, Rd4dev commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/SprayTool.kt
Hi @khalid-nasralla , thanks for the guidance on the coding standards followed. I have made the directed changes and pushed the updated code 😃.

2023-05-31 14:16 UTC, khalid-nasralla approved these changes
Thanks, looks good now.

2023-07-21 14:49 UTC, merged

2024-01-15 07:45 UTC, abhineshchandra1234 commented
Hi @khalid-nasralla @bakicelebi ,

- I am an Android developer with 4 years of experience working for Infosys.
- I would like to contribute to this repository. If you have any tasks for me, please let me know.