PAINTROID-466 Fix OutOfBoundsException at LayerPresenter.getLayerItem()
Catrobat/Paintroid pull request #1281
Opened 2023-05-28 17:03 UTC by khalid-nasralla

I tried to reproduce the bug, but didn't manage to reproduce it as there is also no description on how to reproduce it.  The getLayerItem() is now checked in case we try to access a position that is out of bounds, to avoid the app from crashing in case the bug would occur. I also adapted the code parts where the getLayerItem() is called, in case the method would return null.

This should then hopefully eliminate the problem.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-06-16 14:25 UTC, Lenkomotive approved these changes
👍🏼

2023-06-21 11:09 UTC, SebastianGrief requested changes

2023-06-24 14:17 UTC, khalid-nasralla commented on Paintroid/src/main/java/org/catrobat/paintroid/presenter/LayerPresenter.kt
> +            Log.w("LayerPresente.kt", "LayerPresenter.getLayerItem(position) - tried to access position out of range of the layers array!")
fixed the typo

2023-06-27 12:17 UTC, Lenkomotive approved these changes
👍🏼

2023-06-28 05:04 UTC, SebastianGrief approved these changes
LGTM 👍

2023-06-28 05:04 UTC, merged