PAINTROID-241 Layout errors in right-to-left languages
Catrobat/Paintroid pull request #1300
Opened 2023-07-30 13:29 UTC by khalid-nasralla

[PAINTROID-241](https://jira.catrob.at/browse/PAINTROID-241)

- Removed translation of Bold/Italic/Underline shortcuts for all languages, as they should not be translated according to Material Design (also wouldnt make sense).
- Undo/Redo in top toolbar fixed for RTL languages according to Material Design.
- Undo/Redo arrows pointing in the right direction now according to Material Design.
- Undo/Redo in welcome screen fixed for RTL languages according to Material Design.
- Text Tool: fixed the icons and texts of icons according to Material Design. Also fixed the font size textinput.
- Created a new class called "LanguageHelper" that we can use in case we need to do language specific things like checking if the current language is a RTL language, for code reusability.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-10-30 15:33 UTC, JulianJautz requested changes
Changes look good!
Which source do you have regarding not translating bold, italic and underline?

Is it possible to add a test regarding the rtl layout like suggested in the ticket?

Could you check why so many tests failed on Jenkins and there is a merge conflict, which needs to be solved.

2023-11-20 13:54 UTC, JulianJautz approved these changes

2023-12-29 16:32 UTC, Lenkomotive commented
Please remove the changes in the language-specific files, those are usually handled by crowdin.

2024-02-20 16:02 UTC, Lenkomotive approved these changes
👍🏼

2024-03-20 22:07 UTC, merged