PAINTROID-648 Dynamic animation of top and bottom bar
Catrobat/Paintroid pull request #1302
Opened 2023-08-16 08:04 UTC by Lenkomotive

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-09-11 08:42 UTC, bakicelebi requested changes
Please also animate top and bottom bar when using pipette tool.

2023-09-11 09:03 UTC, bakicelebi approved these changes
Okay, makes sense :+1:

2023-10-28 11:56 UTC, JulianJautz requested changes
Dynamic animation works fine. 
But when using the Smudge tool, the bars are always there. Please add the animation for the Smudge tool.
Regarding, Shape, Clipboard and Text I assume you did not change them on purpose?

2023-10-29 09:43 UTC, Lenkomotive commented
> Dynamic animation works fine. But when using the Smudge tool, the bars are always there. Please add the animation for the Smudge tool. Regarding, Shape, Clipboard and Text I assume you did not change them on purpose?

**Shape, Clipboard and Text:** Yes, thats correct. I left them on purpose since the shapes are usually already big relative to screen size and therefore going into fullscreen mode immediately makes sense.

**Smudge**: I have chosen to omit the animation for the smudge tool. Given its frequent touch events during use, the animation could become disturbing for the user. Also, the line drawn by the smudge tool is typically short and I believe the desired area on the canvas is often visible to the user so that going into fullscreen mode is not that necessary.

2023-10-30 10:47 UTC, JulianJautz commented
> > Dynamic animation works fine. But when using the Smudge tool, the bars are always there. Please add the animation for the Smudge tool. Regarding, Shape, Clipboard and Text I assume you did not change them on purpose?
> 
> **Shape, Clipboard and Text:** Yes, thats correct. I left them on purpose since the shapes are usually already big relative to screen size and therefore going into fullscreen mode immediately makes sense.
> 
> **Smudge**: I have chosen to omit the animation for the smudge tool. Given its frequent touch events during use, the animation could become disturbing for the user. Also, the line drawn by the smudge tool is typically short and I believe the desired area on the canvas is often visible to the user so that going into fullscreen mode is not that necessary.

Makes sense. :)

2023-10-30 10:48 UTC, JulianJautz approved these changes

2023-10-30 10:55 UTC, JulianJautz requested changes
Just one thing: What do you think of adding a "false" default value for shouldAnimate in the  handleMove method in Tool.kt? Then we would not need to change all the test classes.

2023-10-31 10:23 UTC, Lenkomotive commented
> Just one thing: What do you think of adding a "false" default value for shouldAnimate in the handleMove method in Tool.kt? Then we would not need to change all the test classes.

good idea! Done 👍🏼

2023-11-03 13:20 UTC, merged