PAINTROID-676 : Fixed the clipping area bug
Catrobat/Paintroid pull request #1313
Opened 2023-10-09 12:46 UTC by exland

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-10-29 10:29 UTC, Lenkomotive requested changes
The bug seems to be fixed, nice work!

But there seems to be a flaky test now in the ClippingToolIntegrationTest. Please take a look, especially at `testClipBlackBitmapAndThenUndoAndRedo`

2023-10-31 08:58 UTC, exland commented
Thank you for the feedback. 
I took an another look at the flaky test and implemented the fix for it.

2023-10-31 10:13 UTC, Lenkomotive approved these changes

2023-11-01 19:29 UTC, juliajulie95 approved these changes

2023-11-01 19:30 UTC, merged