PAINTROID-444 Show size of shapes in different tools
Catrobat/Paintroid pull request #1325
Opened 2023-12-24 09:46 UTC by JulianJautz

Done for Clipboard-, Shape- and Text-Tool
Chip for current shape size is shown above other tool specific options

https://jira.catrob.at/browse/PAINTROID-444

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-02-29 16:51 UTC, Lenkomotive requested changes

2024-02-29 16:51 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultTextToolOptionsView.kt
> +        textToolOptionsViewShapeSizeChip = textToolView.findViewById<LinearLayout>(R.id.pocketpaint_layout_text_tool_options_view_shape_size).findViewById(R.id.pocketpaint_fill_shape_size_text)
Please try to fit those lines inside the "ruler" for readability.

2024-02-29 16:51 UTC, Lenkomotive commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/tools/DefaultClipboardToolOptionsView.kt
> +            shapeSizeChip = findViewById<LinearLayout>(R.id.pocketpaint_layout_clipboard_tool_options_view_shape_size).findViewById(R.id.pocketpaint_fill_shape_size_text)
Please try to fit those lines inside the "ruler" for readability.

2024-03-15 14:16 UTC, JulianJautz commented
> I noticed a small bug for the tools Clipboard and Shape. When resizing slowly the bug doesnt occur but when I resize a little bit faster, it pushes the size information to the top of the settings as expected but leaves behind the size information where it was previously, [here is a video](https://github.com/Catrobat/Paintroid/assets/71790852/00ac606c-a5a1-41d5-9534-aea87bfd6d54)

This bug was due to the animation of the Chip. I removed the animation now, which fixes the issue (when the movement is too fast, the chip is set invisible before the animation is finished and it gets set visible at the end of the animation again). Drawback, the Chip is visible before the tool options vanish...

2024-03-20 22:03 UTC, Lenkomotive approved these changes
👍🏼

2024-04-30 14:20 UTC, juliajulie95 approved these changes

2024-04-30 14:21 UTC, merged