PAINTROID-681 Smoothing algorithm displays two lines (eraser tool)
Catrobat/Paintroid pull request #1327
Opened 2023-12-29 22:12 UTC by khalid-nasralla

[PAINTROID-681](https://jira.catrob.at/browse/PAINTROID-681)

- Fixed bug where eraser was weirdly readjusting the erased line causing a 2nd erased line to appear when removing the finger from the canvas. (after erasing was done)

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-02-12 14:33 UTC, JulianJautz requested changes
It seems like the smoothing of the eraser lines is now completely turned off. The original line should be removed immediately and only the smoothed one should remain.

2024-02-22 09:29 UTC, JulianJautz commented
> It seems like the smoothing of the eraser lines is now completely turned off. The original line should be removed immediately and only the smoothed one should remain.

As discussed in the meeting yesterday, it is okay to turn off the smoothing for the eraser. If I did not miss something, the handleUpEraser is exactly the same as the handleUp for the Brush tool, with the exception of the if statement for the smoothing algorithm. Maybe we could reuse the existing methods to reduce duplicate code?

2024-03-01 13:06 UTC, JulianJautz approved these changes

2024-04-15 16:11 UTC, juliajulie95 approved these changes

2024-04-15 16:12 UTC, merged