PAINTROID-154 Add "Auto" to crop icon
Catrobat/Paintroid pull request #771
Opened 2020-09-09 08:40 UTC by FromG

added "Auto" to crop icon.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-09 16:15 UTC, ThorstenBandel approved these changes
Look good to me

2020-09-12 01:23 UTC, wslany requested changes
Thanks!

Please change the size and color of the "Auto" text below the crop symbol to those of the "Width" in the same line. The symbol shall also have the same color as the text (same grey). 
![image](https://user-images.githubusercontent.com/1747888/92983920-c4b27680-f4a6-11ea-8f5f-b80288613146.png)

2020-09-12 01:23 UTC, wslany commented on Paintroid/src/main/res/values/string.xml
> +    <string name="transform_auto_crop_text" translatable="false">Auto</string>
```suggestion
    <string name="transform_auto_crop_text">Auto</string>
```

This should also be translatable please.

2020-09-14 16:01 UTC, StanglTobias reviewed
@wslany i would suggest to keep the Auto text and icon in black and rather change the texts of width and height to black because otherwise it looks like it would be disabled to me. Or we could move it to the other transform options

2020-09-30 12:54 UTC, StanglTobias approved these changes

2020-10-09 06:50 UTC, wslany commented
> @wslany i would suggest to keep the Auto text and icon in black and rather change the texts of width and height to black because otherwise it looks like it would be disabled to me. Or we could move it to the other transform options

@StanglTobias you are right, and I agree. I checked the other tools, where such texts are usually in the light blue of the other settings texts and fields, and other elements are either also in the light blue or in black. See, e.g., 
![image](https://user-images.githubusercontent.com/1747888/95551488-2c5ad380-0a0b-11eb-8025-6c3af1c6d2b9.png)

(Actually, I think the circle and square at the bottom in the brush tool settings in the screenshot above should also be in the light blue color --- @ThorstenBandel what do you think? --- but that should be handled in a different ticket, and if so, changed in the other ticket for all relevant places in the tool settings).

In summary, @FromG please change the texts in the transform tool and the "Auto" button to the light blue color. The only element that should remain in grey is the line below the number. Sorry for this, but I think Tobias is right, and let's change it now while we still know where this can be changed.

2020-10-14 18:51 UTC, StanglTobias requested changes

2020-10-14 18:51 UTC, StanglTobias commented on Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
> +                android:textColor="#33B5E5"
please use `android:textColor="?attr/colorAccent"`

2020-10-14 18:51 UTC, StanglTobias commented on Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
> +                android:textColor="#33B5E5"
please use android:textColor="?attr/colorAccent"

2020-10-14 18:51 UTC, StanglTobias commented on Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
> +                android:textColor="#33B5E5"
please use android:textColor="?attr/colorAccent"

2020-10-14 18:51 UTC, StanglTobias commented on Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
> +                android:textColor="#33B5E5"
please use android:textColor="?attr/colorAccent"

2020-10-14 18:51 UTC, StanglTobias commented on Paintroid/src/main/res/layout/dialog_pocketpaint_transform_tool.xml
> +                android:textColor="#33B5E5"
please use android:textColor="?attr/colorAccent"

2020-10-22 09:15 UTC, wslany approved these changes

2020-10-22 09:16 UTC, merged

2020-10-22 09:16 UTC, wslany commented
Thanks!!