Paintroid-158 Add share image button
Catrobat/Paintroid pull request #772
Opened 2020-09-09 13:58 UTC by Electronix1337

Added share image button to the overflow menu.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-23 12:04 UTC, geolas94 approved these changes
lgtm, test failure from jenkins

2020-10-03 19:39 UTC, StanglTobias requested changes

2020-10-03 19:39 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.java
> +			mainActivity.startActivity(Intent.createChooser(shareIntent, "Send image via"));
don't use hardcoded strings that need to be translated. extract **"send image via"** to string resource

2020-10-05 09:18 UTC, StanglTobias approved these changes

2020-10-17 18:15 UTC, wslany requested changes
Crashes with 
10-17 18:10:00.769 E/AndroidRuntime(20033): FATAL EXCEPTION: main
10-17 18:10:00.769 E/AndroidRuntime(20033): Process: org.catrobat.paintroid.independent_20201009_2251, PID: 20033
10-17 18:10:00.769 E/AndroidRuntime(20033): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at org.catrobat.paintroid.FileIO.saveBitmapToCache(FileIO.java:100)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at org.catrobat.paintroid.ui.MainActivityNavigator.startShareImageActivity(MainActivityNavigator.java:142)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at org.catrobat.paintroid.presenter.MainActivityPresenter.shareImageClicked(MainActivityPresenter.java:198)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at org.catrobat.paintroid.MainActivity.onOptionsItemSelected(MainActivity.java:225)
10-17 18:10:00.769 E/AndroidRuntime(20033): 	at android.app.Activity.onMenuItemSelected(Activity.java:3544)

2020-10-21 14:16 UTC, wslany approved these changes

2020-10-21 14:16 UTC, merged

2020-10-21 14:16 UTC, wslany commented
Thanks!