PAINTROID-151: Redesign copy&paste tool options
Catrobat/Paintroid pull request #792
Opened 2020-10-23 14:29 UTC by StanglTobias

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-10 14:59 UTC, Electronix1337 requested changes
I really like the new design of the stamp tool options! But some (hopefully) minor things have to be changed in my opinion. By the way the deletion of the long click is reasonable in my opinion. 

1) If we copy a box content and rotate the phone the paste button is disabled, even though the stamp tool box has the content before rotating.
2) At least for me on API <= 23 the new buttons are not displaying any text at all. [https://ibb.co/Z1Hc5nw](url) and I would also suggest to have a small space between the "Save" and "Discard" button.
3) I'm not quite sure where this happens, but the selected color in the color picker option is not displayed in the background of the "Apply" button. Background of "Apply" button always stays in the same color except when choosing "transparent" then the color is changed to white otherwise, only the text is changed from black to white depending on the selected color.
4) Is there a special reason why "Cut" option was not implemented? We could create an own ticket for that if it's too much for one ticket but I think the feature can be extremely helpful for users.
5) In my opinion it's quite unintuitive how the tool options overall behave, why not just close the tool options window if user presses back and they are currently opened? And we might consider disabling the onclick for stamp tool options, because the options have to be present all the time in order to actively use the tool, so I don't know if hiding the stamp tool options makes sense. It's definitely just a matter of taste but for me it's rather disturbing than helpful.

2020-12-10 17:29 UTC, StanglTobias commented
>     4. Is there a special reason why "Cut" option was not implemented? We could create an own ticket for that if it's too much for >         one ticket but I think the feature can be extremely helpful for users.

There is a seperate ticket for the cut option.


>     5. In my opinion it's quite unintuitive how the tool options overall behave, why not just close the tool options window if user 
>         presses back and they are currently opened? And we might consider disabling the onclick for stamp tool options, because >         the options have to be present all the time in order to actively use the tool, so I don't know if hiding the stamp tool options 
>         makes sense. It's definitely just a matter of taste but for me it's rather disturbing than helpful.

I totally agree with this, but this has nothing in common with this PR. It should be treated in a separate ticket since this one PR did not change the behavior to this.

2020-12-11 09:54 UTC, Electronix1337 approved these changes

2020-12-11 09:54 UTC, Electronix1337 commented on Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
> -			toolController.hideToolOptionsView();
Errors are all fixed, but back to 5) aren't that the lines of code for instantly setting the brush tool when pressing back? On develop branch the behavior is as desired: If option window is open and user presses back, the option window is closed. I would also prefer that brush tool option window gets closed when user touches the drawing surface but that's just a matter of taste again. Going to put it into PO review and let Wolfgang decide if changes are needed or not.

2020-12-11 10:02 UTC, Electronix1337 requested changes
Actually one little thing has to be fixed, for some reason the "transparent" color is displayed as white now. Maybe fix this before I drag the ticket into PO review.

Colorpicker on develop branch:

![color_picker_normal](https://user-images.githubusercontent.com/56889304/101889781-18b12200-3ba0-11eb-842c-1893a35407b1.png)

Colorpicker in this ticket: 

![color_picker_transparent_wrong](https://user-images.githubusercontent.com/56889304/101889882-38484a80-3ba0-11eb-9296-aedd29483744.png)

2020-12-16 15:23 UTC, StanglTobias commented
all tests pass and my local device.

2020-12-17 08:58 UTC, Electronix1337 approved these changes
lgtm, flaky tests on Jenkins, seem to depend on the slave/state of Jenkins, whether these tests fail or not.

2020-12-18 11:46 UTC, merged

2020-12-18 11:46 UTC, wslany commented
Thanks!