PAINTROID-193 Implicit saving of edited image when returning to Catroid
Catrobat/Paintroid pull request #796
Opened 2020-11-04 10:11 UTC by FromG

eliminated the dialog.

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-11-11 11:16 UTC, Electronix1337 requested changes
The two testfiles "OpenedFromPocketCodeWithImageTest" and "OpenedFromPocketCodeWithNewImageTest" are not proper written but I've already done that on Ticket 194 - Check all tests for correct behavior. I am going to adjust these tests when this ticket is merged into develop but I think you might want to change
`if (isImageUnchanged() || model.isSaved())` in MainActivityPresenter line 176 to
`if (isImageUnchanged() || model.isSaved() || model.isOpenedFromCatroid())`
 if I'm not mistaken so the save dialog is not shown when exiting the application when opened from catroid is true.

2020-11-16 09:02 UTC, Electronix1337 requested changes
testBrushToolBackPressedFromCatroidAndUsePicture in ToolOnBackPressedIntegrationTest.java can be deleted in my opinion because it tests the same as OpenedFromPocketCode and testBrushToolBackPressedFromCatroidAndDiscardPicture should be deleted because this is not possible anymore due to implicit saving. I would also suggest to adjust the OpenedFromPocketCodeNewImageTest.testSave because the save dialog should not show up and therefore the test has to be rewritten. In the current version the "openedfromcatroid" flag is not even set. And we should clarify if implicit saving from catroid should be done with png/jpg or if we let the user decide which would make the implicit saving kind of redundant? @wslany

2020-12-11 06:34 UTC, wslany requested changes
Currently this is difficult to test because it cannot be built with Catroid, see for instance in https://jenkins.catrob.at/job/Paintroid/job/PR-796/6/execution/node/43/log/ when you set the parameter yes for the build with Catroid in the build with parameter interface
```
07:27:37  FAILURE: Build failed with an exception.
07:27:37  
07:27:37  * What went wrong:
07:27:37  Execution failed for task ':catroid:processCatroidDebugManifest'.
07:27:37  > Manifest merger failed : Attribute application@name value=(org.catrobat.catroid.CatroidApplication) from AndroidManifest.xml:88:9-43
07:27:37    	is also present at [org.catrobat.paintroid:paintroid:2.5.2-LOCAL] AndroidManifest.xml:39:9-61 value=(androidx.multidex.MultiDexApplication).
07:27:37    	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:34:5-44:19 to override.
07:27:37  
```
![image](https://user-images.githubusercontent.com/1747888/101871044-1f7d6c00-3b83-11eb-966d-393a64b9272e.png)

To run this, you need to be logged in in jenkins and press here:
![image](https://user-images.githubusercontent.com/1747888/101871127-4cca1a00-3b83-11eb-89a7-7e74b8357c18.png)

2020-12-11 18:16 UTC, wslany requested changes
@FromG I just tried this with https://jenkins.catrob.at/job/Paintroid/job/PR-796/9/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug.apk : when I edit a look in a project, then return to the IDE part of Pocket Code, the changes are not there. I.e., the implicit saving is not done. All changes seem to be ignored. Also, when I try to add a new object and choose to draw it with Paintroid in Catroid, after going back out of Paintroid, there is no new object, all drawings are lost.

2020-12-16 10:02 UTC, Electronix1337 approved these changes
lgtm

2020-12-16 12:30 UTC, wslany approved these changes

2020-12-16 12:50 UTC, wslany requested changes
Perfect, thanks!! We can merge this PR once https://jira.catrob.at/browse/CATROID-761 has been implemented and merged, which is blocking the present ticket. We'll park the present ticket and PR in PO review until the Catroid ticket has been merged, hopefully soon. I mark the PR as "request change" so that nobody inadvertently merges it before the Catroid ticket has been merged.

2020-12-28 19:04 UTC, wslany approved these changes

2020-12-28 19:04 UTC, merged

2020-12-28 19:04 UTC, wslany commented
Thanks!!