PAINTROID-139 Using certain tools should not reset the center and zoom level of the canvas
Catrobat/Paintroid pull request #798
Opened 2020-11-12 13:37 UTC by Electronix1337

Implemented that perspective scale does not reset when choosing certain tools (text, shape, transform, importpng, stamp) and the tool box gets placed in the middle of the screen if scale > 1 (if zoomed). Also added tests to check behavior for affected tools. https://jira.catrob.at/browse/PAINTROID-139

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-11-13 11:09 UTC, FromG requested changes

2020-11-13 11:09 UTC, FromG commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
> +//		resetScaleAndTranslation();
delete line if not needed
in: Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/TransformTool.java
`//		resetScaleAndTranslation();`

2020-11-13 14:03 UTC, FromG approved these changes
lgtm.

2020-12-09 20:36 UTC, merged

2020-12-09 20:36 UTC, wslany commented
Thanks!