PAINTROID-202 : refactored dialogs
Catrobat/Paintroid pull request #808
Opened 2020-12-25 21:57 UTC by FromG

refactored the dialogs as described in the ticket.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-28 10:34 UTC, Electronix1337 approved these changes
Lgtm. Everything works the same as on the develop branch.

2020-12-28 12:38 UTC, StanglTobias requested changes
seems like you do use spaces for indentation. please change to tabs

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/AboutDialog.kt
> +        } else inflater.inflate(R.layout.dialog_pocketpaint_about, container, false)
please do note leave curly brackets

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/AboutDialog.kt
> +        val inflater = activity!!.layoutInflater
use requireActivity when ever possible

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/AboutDialog.kt
> +        return AlertDialog.Builder(context!!, R.style.PocketPaintAlertDialog)
use requireContext when ever possible

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/AboutDialog.kt
> +        }
change to fun newInstance(): AboutDialog = AboutDialog()

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/FeedbackDialog.kt
> +        }
same as aboutdialog

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/ImportImageDialog.kt
> +    }
same as aboutdialog

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/IndeterminateProgressDialog.kt
> +    }
```
return AlertDialog.Builder(context!!, R.style.PocketPaintProgressDialog)
        .setCancelable(false)
        .setView(R.layout.pocketpaint_layout_indeterminate)
        .create()
```

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +        val arguments = arguments
not necassary to create a local variable

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +        }
idiomatic kotlin would be

```
arguments?.let {
 ....
}
```

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +            bundle.putInt(TITLE_RESOURCE_KEY, titleResource)
have a look at kotlin `apply()` function

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/LikeUsDialog.kt
> +        }
same as aboutdialog

2020-12-28 12:38 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +		fun newInstance(dialogType: DialogType, @StringRes messageResource: Int, @StringRes titleResource: Int): InfoDialog {
indentation does not look correct here

2020-12-29 15:47 UTC, StanglTobias requested changes

2020-12-29 15:47 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +	}
please reformat this

2020-12-29 15:47 UTC, StanglTobias commented on Paintroid/src/main/java/org/catrobat/paintroid/dialog/InfoDialog.kt
> +		}
```
return InfoDialog().apply {
      arguments = bundleof( ... )
}
```

would be even nicer but you dont have to change it

2020-12-30 14:53 UTC, StanglTobias approved these changes

2021-01-04 15:02 UTC, merged