PAINTROID-141 No feedback where images are saved or copied to
Catrobat/Paintroid pull request #870
Opened 2021-04-09 14:04 UTC by CodeChamp-SS

Added the place in the file system where the image or copy was saved in the bubble.

https://jira.catrob.at/browse/PAINTROID-141

<img src="https://user-images.githubusercontent.com/52480794/114191551-2b7b0e00-996a-11eb-93b0-285182e3478d.png" width="400" height="700"/>

<img src="https://user-images.githubusercontent.com/52480794/114191477-156d4d80-996a-11eb-8503-a763c3348bc7.png" width="400" height="700"/>

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-10 16:06 UTC, wslany requested changes
Nice. 

Please fix the lint warnings https://jenkins.catrob.at/job/Paintroid/job/PR-870/1/analysis/

Lots of post-save and post-copy tests are failing now, see https://jenkins.catrob.at/job/Paintroid/job/PR-870/1/testReport/

Also, please add an automatic test that checks the new behavior.

On Android 6.0 on a Samsung Galaxy S7, no destination is shown:
![image](https://user-images.githubusercontent.com/1747888/114273265-ac451300-9a19-11eb-983f-0b890015a61e.png)

Same also on Android 7.1 and Android 8, both on a Google Pixel phone, as well as Android 9 on a Pixel 3a XL, no path information is shown in the toast:
![image](https://user-images.githubusercontent.com/1747888/114276364-968a1a80-9a26-11eb-8f7f-892329eda4cd.png)
![image](https://user-images.githubusercontent.com/1747888/114276450-e5d04b00-9a26-11eb-8fdb-dbb78dae8341.png)
![image](https://user-images.githubusercontent.com/1747888/114276527-46f81e80-9a27-11eb-844a-becf84723c43.png)

It seems to work only on Android 10 and 11.

2021-04-10 19:07 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/presenter/MainActivityPresenter.java
>  			model.setSavedPictureUri(uri);
ok

2021-04-10 19:39 UTC, CodeChamp-SS commented
> Nice.
> 
> Please fix the lint warnings https://jenkins.catrob.at/job/Paintroid/job/PR-870/1/analysis/
> 
> Lots of post-save and post-copy tests are failing now, see https://jenkins.catrob.at/job/Paintroid/job/PR-870/1/testReport/
> 
> Also, please add an automatic test that checks the new behavior.
> 
> On Android 6.0 on a Samsung Galaxy S7, no destination is shown:
> ![image](https://user-images.githubusercontent.com/1747888/114273265-ac451300-9a19-11eb-983f-0b890015a61e.png)
> 
> Same also on Android 7.1 and Android 8, both on a Google Pixel phone, as well as Android 9 on a Pixel 3a XL, no path information is shown in the toast:
> ![image](https://user-images.githubusercontent.com/1747888/114276364-968a1a80-9a26-11eb-8f7f-892329eda4cd.png)
> ![image](https://user-images.githubusercontent.com/1747888/114276450-e5d04b00-9a26-11eb-8fdb-dbb78dae8341.png)
> ![image](https://user-images.githubusercontent.com/1747888/114276527-46f81e80-9a27-11eb-844a-becf84723c43.png)
> 
> It seems to work only on Android 10 and 11.

hmm, I'l try to fix the issues soon.

2021-04-11 04:22 UTC, CodeChamp-SS commented
I think now the failing tests should pass, and I've also added tests for checking the new behavior.

2021-04-11 04:26 UTC, CodeChamp-SS commented
@wslany sir, can you please recheck the new behavior on different versions of android? I hope it should work fine now : )

2021-04-11 04:55 UTC, CodeChamp-SS commented
I reformatted the whole MainActivityPresenter Class using android studio's code formatting functionality, but still, it's showing lint warnings, I think there is some problem with the Jenkins static analysis tool 🤔

2021-04-17 12:40 UTC, CodeChamp-SS commented
@wslany sir, now it doesn't show any new warnings and I hope it should work fine now for different versions of android as well. Can you please review it once again?

2021-04-17 13:52 UTC, wslany commented
🙏 @CodeChamp-SS could you cross-review @chbinder 's #857 PR which is also in code review? It is just one line further, see https://jenkins.catrob.at/job/Paintroid/job/PR-870/8/testReport/org.catrobat.paintroid.test.espresso/MenuFileActivityIntegrationTest/Tests___Device_Tests___testSaveCopy/ but actually is already occurring long before your pull request.

2021-04-17 14:27 UTC, wslany commented
> 🙏 @CodeChamp-SS could you cross-review @chbinder 's #857 PR which is also in code review? It is just one line further, see https://jenkins.catrob.at/job/Paintroid/job/PR-870/8/testReport/org.catrobat.paintroid.test.espresso/MenuFileActivityIntegrationTest/Tests___Device_Tests___testSaveCopy/ but actually is already occurring long before your pull request.

@CodeChamp-SS another possibility for a cross-review of each other's tickets is #858 of @harsh-hash

2021-04-17 14:47 UTC, ThorstenBandel approved these changes
LGTM

2021-04-17 14:47 UTC, CodeChamp-SS commented
> 🙏 @CodeChamp-SS could you cross-review @chbinder 's #857 PR which is also in code review? It is just one line further, see https://jenkins.catrob.at/job/Paintroid/job/PR-870/8/testReport/org.catrobat.paintroid.test.espresso/MenuFileActivityIntegrationTest/Tests___Device_Tests___testSaveCopy/ but actually is already occurring long before your pull request.

I think changes made by @chbinder in testSaveCopy should fix it.

2021-04-18 14:33 UTC, merged

2021-04-18 14:33 UTC, wslany commented
Thanks!!