PAINTROID-237 fixed ActivityNotFound when rating the app
Catrobat/Paintroid pull request #883
Opened 2021-04-21 16:25 UTC by ldirry

Fixed ActivityNotFoundException when the user tries to rate this app but no app is registered for handling the intent.

https://jira.catrob.at/browse/PAINTROID-237

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-21 16:33 UTC, ldirry commented
Should a toast message be displayed when no app can be found for handling the intent? (They honestly feel a bit cheap to me but at least the user gets feedback)

2021-04-30 09:24 UTC, ThorstenBandel approved these changes
LGTM

2021-05-10 13:38 UTC, wslany requested changes
I just tried this on a device without app store installed, and the app closed and I returned to the Android home screen when I tried to rate Pocket Paint. Unfortunately I did not get a stack trace. Here the details about the phone:
![image](https://user-images.githubusercontent.com/1747888/117667005-bb4bec00-b1a4-11eb-984b-45c297d07364.png)

Same also on these devices:
![image](https://user-images.githubusercontent.com/1747888/117667644-5d6bd400-b1a5-11eb-887b-c474164f83f3.png)

![image](https://user-images.githubusercontent.com/1747888/117667371-1da4ec80-b1a5-11eb-81dc-7846eaff9965.png)

I checked with the develop branch with these phones, and the behavior was exactly the same, so the PR seems not to have changed anything. What to do?

2021-05-13 07:25 UTC, CodeChamp-SS approved these changes
LGTM 👍🏻

2021-05-13 07:26 UTC, wslany approved these changes

2021-05-13 07:26 UTC, merged

2021-05-13 07:34 UTC, wslany commented
Thanks!

2021-05-13 07:40 UTC, wslany commented
> I also tested it now on browserstack with these devices. The problem seems to be that browserstack doesn't allow these app stores to be opened. If you try opening the AppGalery on Huawai or App Store on the oppo device, the stores will immedately get minimized. (Opening Google play store on the Pixel 4 (for example) seems to be allowed).
>
> But the pocket paint actually never crashes, when opening one of these stores, for example you can draw a line in pocket paint, then rate pocket paint (device will go back to home screen) and then you can reopen the app and the line is still there. On the oppo device you can kinda see the minimize animation, that gets triggered when the home screen button gets pressed, I assume this is how they handle the scenario when opening an app, you don't have permission for. (It all feels a bit buggy and laggy though).

Thanks, yeah I also saw that Browserstack is very laggy with these devices. I wrote to the browserstack support this message:
> Hi, we just found that we cannot access the Huawei AppGallery on the Huawei device. Same also on Oppo's app store. The app store apps immediately close when we open them. It would be nice to be able to check that the connection to them work via intent as we want to be able to see whether our app redirects to the correct app store depending on the device. Thanks and all the best, Wolfgang

2021-05-13 11:28 UTC, wslany commented
Answer from Browserstack support:
> Access to the default applications has been restricted on our Oppo, Huawei and Vivo devices at the moment, but our team is working towards adding support for the same.