PAINTROID-260 Refactor BaseTool and FillTool to Kotlin
Catrobat/Paintroid pull request #912
Opened 2021-05-31 09:08 UTC by CodeChamp-SS

Refactor BaseTool and FillTool to Kotlin.

https://jira.catrob.at/browse/PAINTROID-260

Files that were refactored:

1. BaseTool
2. BaseToolWithShape
3. FillTool
4. FillToolOptionsView
5. SprayTool
6. LineTool

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-06-02 11:03 UTC, gPathpp requested changes

2021-06-02 14:00 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/BaseToolWithShape.kt
> +    }
sure

2021-06-02 14:01 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.kt
> +    companion object {
sure

2021-06-02 14:03 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
> +    override fun draw(canvas: Canvas?) {
I made this change, as the draw function is also being overriden in SprayTool, and there the definition had `?`, so I added here too, as the function definition had to be the same

2021-06-02 14:03 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
> +    override fun draw(canvas: Canvas?) {
Also I thought that it would be just an extra safety towards null entries, so I didn't think of removing that `?` from SprayTool file :)

2021-06-02 15:14 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/FillTool.kt
> +    var colorTolerance = MAX_ABSOLUTE_TOLERANCE * DEFAULT_TOLERANCE_IN_PERCENT / 100.0f
no, see line 62

2021-06-07 12:00 UTC, gPathpp commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
> +    override fun draw(canvas: Canvas?) {
Please check if ? can be removed from SprayTool.

2021-06-07 14:47 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/implementation/LineTool.kt
> +    override fun draw(canvas: Canvas?) {
ok, so after checking it's, I think ? can be removed.

2021-06-07 17:04 UTC, gPathpp approved these changes

2021-06-18 08:34 UTC, merged

2021-06-18 08:35 UTC, wslany commented
Thanks!