PAINTROID-265 Refactor TextTool to Kotlin
Catrobat/Paintroid pull request #952
Opened 2021-06-29 12:51 UTC by CodeChamp-SS

Files that were refactored:

1. TextTool
2. TextToolOptionsView

https://jira.catrob.at/browse/PAINTROID-265

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-05 14:00 UTC, geolas94 requested changes

2021-07-05 16:28 UTC, geolas94 approved these changes

2021-07-05 16:28 UTC, geolas94 approved these changes
lgtm

2021-07-13 16:08 UTC, ThorstenBandel commented
There are static analysis errors and warnings, could you please fix them ? :)

2021-07-13 16:55 UTC, CodeChamp-SS commented
> There are static analysis errors and warnings, could you please fix them ? :)

sure

2021-07-13 17:46 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/tools/options/TextToolOptionsView.kt
> +        fun setText(text: String)
added the empty lines :)

2021-07-26 15:30 UTC, wslany commented
Pls could you once more resolve the conflicts?

2021-08-08 10:44 UTC, ThorstenBandel approved these changes
Lgtm :D

2021-08-08 10:44 UTC, merged