PAINTROID-303 Refactor CatroidMediaGalleryFragment to Kotlin
Catrobat/Paintroid pull request #964
Opened 2021-07-12 11:47 UTC by CodeChamp-SS

The file that was refactored: CatroidMediaGalleryFragment

https://jira.catrob.at/browse/PAINTROID-303

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-23 09:46 UTC, Electronix1337 requested changes

2021-07-23 09:46 UTC, Electronix1337 commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/fragments/CatroidMediaGalleryFragment.kt
> +                        override fun onLoadingComplete(imageUri: String, view: View, loadedImage: Bitmap?) {
Tested the CatroidMediaGalleryFragment and when selecting a picture from the sticker store, the app crashes with a NPE. This is due to the fact that view: View is not declared nullable view: View? but actually is null. As you do not need it in the function, I'd suggest just setting the parameter as nullable and then everything should work as intended.

2021-07-26 08:18 UTC, Electronix1337 approved these changes
NPE doesn't occur anymore, nice! Am I the only one that can't test the sticker import on API's < 28 due to the fact that the app is stuck at this point of importing the sticker? 
![progress_bar_sticker_import](https://user-images.githubusercontent.com/56889304/126952556-042cf2d4-5d46-49aa-9d84-ce397450b1b7.png)

Is also present on develop branch for me but this seems to be a emulator bug as it works for others.

2021-07-31 16:46 UTC, ldirry approved these changes
Nice 👍 , looks good to me.

2021-07-31 16:46 UTC, merged