PAINTROID-149 better image Better png compression (Research and implementation)
Catrobat/Paintroid pull request #968
Opened 2021-07-13 09:37 UTC by barcodepony

[PAINTROID-149 Better png compression](https://jira.catrob.at/browse/PAINTROID-149)

- added id.zelory.compressor.Compressor library for compression
- saving images temporary in the cache if needed for compression
- added support for Android Q (files are handled differently)
- added compression test

### Your checklist for this pull request

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-19 09:26 UTC, FromG requested changes
On Android API 30
SaveCompressionImageIntegrationTest
- testSaveImage always fails locally on my device because of the following exception:
    'int android.graphics.Bitmap.getWidth()'
maybe look at changes in the different api versions for Files/Filesystem

Rebase conflicts from develop 
Maybe squash commits.

Rest looks good

2021-07-20 13:22 UTC, FromG approved these changes
ok

2021-08-10 02:46 UTC, wslany commented
@barcodepony please could you resolve the conflict?

2021-08-17 09:45 UTC, wslany commented
@barcodepony please also squash the commits.

2021-11-02 16:44 UTC, closed without merging