PAINTROID-314 Refactor MainActivityNavigator to Kotlin
Catrobat/Paintroid pull request #974
Opened 2021-07-15 14:04 UTC by CodeChamp-SS

Refactored `MainActivityNavigator` to Kotlin.

Replaced the deprecated `ACTION_MEDIA_SCANNER_SCAN_FILE` intent with `MediaScannerConnections` (reference: https://stackoverflow.com/questions/60203353/action-media-scanner-scan-filestring-is-deprecated)

Removed `@JvmStatic` annotation which is no longer required, and refactored the following dialog classes:

1. AboutDialog
2. FeedbackDialog
3. ImportImageDialog
4. InfoDialog
5. LikeUsDialog
6. OverwriteDialog
7. SaveInformationDialog
8. ScaleImageOnLoadDialog

https://jira.catrob.at/browse/PAINTROID-314

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-07-15 14:40 UTC, gPathpp requested changes
LGTM 👍
Just one small change please :)

2021-07-15 14:40 UTC, gPathpp commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
> +        if (uri != null) {
```suggestion
        val uri = FileIO.saveBitmapToCache(bitmap, mainActivity) ?: return
```

2021-07-15 15:39 UTC, CodeChamp-SS commented on Paintroid/src/main/java/org/catrobat/paintroid/ui/MainActivityNavigator.kt
> +        if (uri != null) {
done :)

2021-07-15 15:46 UTC, gPathpp approved these changes

2021-07-25 11:10 UTC, ldirry commented
This doesn't seem to be related with this PR but there is currently a bug on develop.

If you save an image as png first and then save it another time to jpg, it will get saved as <image-name>.png with jpg compression. Same if you save it as .jpg first and the second time as .png.

Is this an easy fix, would be nice if we could include it then? Else the PR looks good to me :)

2021-07-26 15:31 UTC, wslany commented
Please also resolve conflicts.

2021-07-26 15:33 UTC, CodeChamp-SS commented
> Please also resolve conflicts.

sure, will resolve them soon, also need to look into the thing Lorenz mentioned :)

2021-07-28 16:05 UTC, ldirry approved these changes
This bug: https://jira.catrob.at/browse/PAINTROID-344 wasn't introduced with this PR and we don't know a quick fix yet. PR looks good to me :). Merged.

2021-07-28 16:05 UTC, merged

2021-07-28 20:01 UTC, ldirry commented
ah damn, my bad, I didn't see that the `testSaveAndOverrideOraFile` was crashing with this PR, reverted the merge sry...  do you maybe know how to fix this testcase? :)